# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a24235adb32beb1158360e1674044dca4122cdcf8666ca6f807e40d5e5879d362774955e6032a50cf8d451f1aa9af73d1b26b6e80f8a1f036b0142286e03d6

test:
  secret_key_base: c5a306562ac6fed66576b7a177f1781465bae38be07b97c2cfa5da56188af0b6c5b0535b270a7c0c3295563a4549b9e4b56c24f9f1d6ca76a23b96ae91196dda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
